# Generated by Django 3.0.6 on 2020-08-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactfrontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
