# Generated by Django 3.0.6 on 2020-09-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='AssetStatus',
            field=models.CharField(default='Ready', max_length=30),
        ),
    ]
