# Generated by Django 3.0.6 on 2020-09-15 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_assetstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='SerialNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
