# Generated by Django 3.0.6 on 2020-09-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='Company',
        ),
    ]
