# Generated by Django 3.0.6 on 2020-09-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_assetcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='DeviceModel',
            field=models.CharField(default='unassigned', max_length=30),
        ),
        migrations.AddField(
            model_name='asset',
            name='HardDrive',
            field=models.CharField(default='unassigned', max_length=30),
        ),
        migrations.AddField(
            model_name='asset',
            name='Ram',
            field=models.CharField(default='unassigned', max_length=30),
        ),
        migrations.AddField(
            model_name='asset',
            name='ScreenSize',
            field=models.CharField(default='unassigned', max_length=30),
        ),
        migrations.AddField(
            model_name='asset',
            name='Year',
            field=models.CharField(default='unassigned', max_length=30),
        ),
    ]
