# Generated by Django 3.0.6 on 2020-09-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='AssetTag',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
