# Generated by Django 3.0.6 on 2020-09-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20200921_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='AssetTag',
            field=models.CharField(max_length=30),
        ),
    ]
