# Generated by Django 3.0.6 on 2020-09-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200914_1300'),
        ('assets', '0006_asset_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('AssetTag', 'Company')},
        ),
    ]
