# Generated by Django 3.0.6 on 2020-09-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200914_1300'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthorizeduser',
            name='Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
