# Generated by Django 3.0.6 on 2020-09-22 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0002_auto_20200918_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unauthorizeduser',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='unauthorizeduser',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='unauthorizeduser',
            name='Username',
        ),
        migrations.AddField(
            model_name='unauthorizeduser',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
