# Generated by Django 3.0.6 on 2020-09-28 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0003_auto_20200914_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetTag', models.CharField(max_length=30)),
                ('DeviceType', models.CharField(default='Laptop', max_length=30)),
                ('AssetStatus', models.CharField(default='Ready', max_length=30)),
                ('SerialNumber', models.CharField(max_length=64, unique=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('AssetTag', 'Company')},
            },
        ),
    ]
