# Generated by Django 3.0.6 on 2020-10-07 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=30)),
                ('device_type', models.CharField(default='Laptop', max_length=30)),
                ('device_model', models.CharField(default='unassigned', max_length=30)),
                ('asset_status', models.CharField(default='Ready', max_length=30)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('asset_condition', models.CharField(default='Good', max_length=30)),
                ('screen_size', models.CharField(default='unassigned', max_length=30)),
                ('hard_drive', models.CharField(default='unassigned', max_length=30)),
                ('ram', models.CharField(default='unassigned', max_length=30)),
                ('year', models.CharField(default='unassigned', max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('asset_tag', 'company')},
            },
        ),
    ]
