# Generated by Django 3.0.6 on 2020-09-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='AssetCondition',
            field=models.CharField(default='Good', max_length=30),
        ),
    ]
