# Generated by Django 3.0.7 on 2021-03-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20210304_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(default=None, max_length=64, null=True, unique=True),
        ),
    ]
