# Generated by Django 3.0.6 on 2020-09-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_auto_20200914_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=40)),
                ('Body', models.CharField(max_length=300)),
                ('Time_Created', models.DateTimeField(auto_now_add=True)),
                ('Admin_Only', models.BooleanField(default=False)),
                ('Action_Required', models.BooleanField(default=False)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
